jobs:
  action:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Init
        uses: actions/checkout@v2
      - name: Fetch Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./main/main

name: Main

on:
  schedule:
    - cron: "55 0/3 * * *"
